# Architectire for a CAD systems.

# diagram settings...
direction: right

# heading...
Architecture - Cad Systems: {
  shape: text
  near: top-center
  style: {
    font-size: 55
  }
}

# components used in cad generation...

root_components: {
  Params: {
    shape: stored_data
  }

  CadGeneratedRoot: {
    shape: stored_data
  }
}

mesh_components: {
  CadGeneratedMesh: {
    shape: stored_data
  }

  BelongsToCadGeneratedMesh: {
    shape: stored_data
  }

  BelongsToCadGeneratedRoot: {
    shape: stored_data
  }

  CadGeneratedMeshOutlines: {
    shape: stored_data
  }

  CadGeneratedMeshOutlinesState: {
    shape: stored_data
  }

  # native...

  'Handle<Mesh>': {
    shape: stored_data
  }

  'Handle<StandardMaterial>': {
    shape: stored_data
  }

  Transform: {
    shape: stored_data
  }
}

cursor_components: {
  CadGeneratedCursor: {
    shape: stored_data
  }

  BelongsToCadGeneratedRoot: {
    shape: stored_data
  }

  CadGeneratedCursorConfig: {
    shape: stored_data
  }

  CadGeneratedCursorState: {
    shape: stored_data
  }

  CadGeneratedCursorPreviousTransform: {
    shape: stored_data
  }

  BelongsToCadGeneratedCursor: {
    shape: stored_data
  }

  CadGeneratedCursorDragPlane: {
    shape: stored_data
  }

  # native...

  Transform: {
    shape: stored_data
  }
}

# evenst used in cad generation...

GenerateCadModel: {
  shape: queue
}

# systems used in cad generation...

model_systems: {
  generate_cad_model_on_event: {
    shape: parallelogram
  }

  update_cad_model_on_params_change: {
    shape: parallelogram
  }
}

# connections...

# event...
GenerateCadModel -> model_systems.generate_cad_model_on_event
# root...
root_components.Params -> model_systems.generate_cad_model_on_event
root_components.CadGeneratedRoot -> model_systems.generate_cad_model_on_event

# root..
root_components.CadGeneratedRoot -> model_systems.update_cad_model_on_params_change
root_components.BelongsToCadGeneratedRoot -> model_systems.update_cad_model_on_params_change
# mesh...
mesh_components.CadGeneratedMesh -> model_systems.update_cad_model_on_params_change
mesh_components.BelongsToCadGeneratedMesh -> model_systems.update_cad_model_on_params_change
# cursor
cursor_components.CadGeneratedCursor -> model_systems.update_cad_model_on_params_change: query_cursors
cursor_components.Transform -> model_systems.update_cad_model_on_params_change: query_cursors
cursor_components.CadGeneratedCursorPreviousTransform -> model_systems.update_cad_model_on_params_change: query_cursors
cursor_components.CadGeneratedCursorState -> model_systems.update_cad_model_on_params_change: query_cursors
